[package]
name = "client"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

[dependencies]
protocol = { path = "../protocol", version = "0.1"}
util = { path = "../util", version = "0.1"}
r2d2 = "0.8"
