[package]
name = "simple-kv-server"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

[dependencies]
engine = { path = "../engine", version = "0.1"}
protocol = { path = "../protocol", version = "0.1"}
util = { path = "../util", version = "0.1"}