language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta

install:
  - cargo install bronzedb-memory-db-server

before_script:
  - echo "db_addr = \"127.0.0.1:8088\"" > Settings.toml
  - bronzedb-memory-db-server &

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --nocapture --test-threads=1