[workspace]
members = [
    "bronzedb",
    "bronzedb-engine",
    "bronzedb-memory-db-server",
    "bronzedb-sled-db-server",
    "bronzedb-protocol",
    "bronzedb-util",
    "bronzedb-client",
    "bronzedb-server",
    "tests"
]
