[package]
name = "protocol"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
util = { path = "../util", version = "0.1"}
matches = "0.1"
